{{- $name := include "downscaler.backend.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    chart: {{ template "downscaler.chart" . }}
    component: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ .Release.Name }}
      component: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ .Release.Name }}
        component: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.backend.name }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: BACKEND_HOST
              value: {{- if .Values.redis.enabled }} {{ .Release.Name }}-redis-master:6379{{- else }} {{ .Values.backend.config.host }}{{ end }}
          envFrom:
            - secretRef:
                name: {{ $name }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
