{{- $name := include "downscaler.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "downscaler.fullname" . }}
  labels:
    app: {{ $name }}
    chart: {{ template "downscaler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.service.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        app: {{ $name }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.downscaler.serviceAccountName | quote }}
      volumes:
        - name: {{ $name }}-config
          configMap:
            name: {{ $name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.downscaler.metricsPort }}
          envFrom:
            - secretRef:
                name: {{ $name }}
          volumeMounts:
            - name: {{ $name }}-config
              mountPath: /etc/downscaler
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
