apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "downscaler.name" . }}
    chart: {{ template "downscaler.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.downscaler.serviceAccountName }}
